title: Product

columns:
  # MAIN
  left:
    width: 2/3
    sections:
      # IMAGE FILES
      pdescription:
        headline: description
        type: fields
        fields:
          description:
            type: writer
            disabled: true

  right:
    width: 1/3
    sections:
      # IMAGE FILES
      details:
        headline: Details
        type: fields
        fields:
          productstatus:
            type: text
            label: Lemon Squeezy Status
            disabled: true

          formattedprice:
            type: text
            label: Price
            disabled: true
